// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\Sementation_8K\K_Means_ip_axi4_stream_video_master.v
// Created: 2019-03-29 13:41:20
// 
// Generated by MATLAB 9.6 and HDL Coder 3.14
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: K_Means_ip_axi4_stream_video_master
// Source Path: K_Means_ip/K_Means_ip_axi4_stream_video_master
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module K_Means_ip_axi4_stream_video_master
          (clk,
           reset,
           enb,
           AXI4_Stream_Video_Master_TREADY,
           user_pixel,
           user_ctrl_hStart,
           user_ctrl_hEnd,
           user_ctrl_vStart,
           user_ctrl_vEnd,
           user_ctrl_valid,
           AXI4_Stream_Video_Master_TDATA,
           AXI4_Stream_Video_Master_TVALID,
           AXI4_Stream_Video_Master_TLAST,
           AXI4_Stream_Video_Master_TUSER,
           auto_ready);


  input   clk;
  input   reset;
  input   enb;
  input   AXI4_Stream_Video_Master_TREADY;  // ufix1
  input   [31:0] user_pixel;  // ufix32
  input   user_ctrl_hStart;  // ufix1
  input   user_ctrl_hEnd;  // ufix1
  input   user_ctrl_vStart;  // ufix1
  input   user_ctrl_vEnd;  // ufix1
  input   user_ctrl_valid;  // ufix1
  output  [31:0] AXI4_Stream_Video_Master_TDATA;  // ufix32
  output  AXI4_Stream_Video_Master_TVALID;  // ufix1
  output  AXI4_Stream_Video_Master_TLAST;  // ufix1
  output  AXI4_Stream_Video_Master_TUSER;  // ufix1
  output  auto_ready;  // ufix1


  wire fifo_afull_data;  // ufix1
  wire internal_ready;  // ufix1
  reg  internal_ready_delayed;  // ufix1
  wire fifo_push;  // ufix1
  wire fifo_empty_data;  // ufix1


  assign internal_ready =  ~ fifo_afull_data;



  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        internal_ready_delayed <= 1'b0;
      end
      else begin
        if (enb) begin
          internal_ready_delayed <= internal_ready;
        end
      end
    end



  assign fifo_push = internal_ready_delayed & user_ctrl_valid;



  K_Means_ip_fifo_data_OUT u_K_Means_ip_fifo_data_OUT_inst (.clk(clk),
                                                            .reset(reset),
                                                            .enb(enb),
                                                            .In(user_pixel),  // ufix32
                                                            .Push(fifo_push),  // ufix1
                                                            .Pop(AXI4_Stream_Video_Master_TREADY),  // ufix1
                                                            .Out(AXI4_Stream_Video_Master_TDATA),  // ufix32
                                                            .Empty(fifo_empty_data),  // ufix1
                                                            .AFull(fifo_afull_data)  // ufix1
                                                            );

  assign AXI4_Stream_Video_Master_TVALID =  ~ fifo_empty_data;



  K_Means_ip_fifo_eol_out u_K_Means_ip_fifo_eol_out_inst (.clk(clk),
                                                          .reset(reset),
                                                          .enb(enb),
                                                          .In(user_ctrl_hEnd),  // ufix1
                                                          .Push(fifo_push),  // ufix1
                                                          .Pop(AXI4_Stream_Video_Master_TREADY),  // ufix1
                                                          .Out(AXI4_Stream_Video_Master_TLAST)  // ufix1
                                                          );

  K_Means_ip_fifo_sof_out u_K_Means_ip_fifo_sof_out_inst (.clk(clk),
                                                          .reset(reset),
                                                          .enb(enb),
                                                          .In(user_ctrl_vStart),  // ufix1
                                                          .Push(fifo_push),  // ufix1
                                                          .Pop(AXI4_Stream_Video_Master_TREADY),  // ufix1
                                                          .Out(AXI4_Stream_Video_Master_TUSER)  // ufix1
                                                          );

  assign auto_ready = internal_ready;

endmodule  // K_Means_ip_axi4_stream_video_master

