// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\Sementation_8K\K_Means_ip_src_MATLAB_Function.v
// Created: 2019-03-29 13:41:03
// 
// Generated by MATLAB 9.6 and HDL Coder 3.14
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: K_Means_ip_src_MATLAB_Function
// Source Path: Sementation_8K/Segmentation_HW/K-Means/Clustering/MATLAB Function
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module K_Means_ip_src_MATLAB_Function
          (vstart,
           fr_num,
           addr,
           rgb_0,
           rgb_1,
           rgb_2,
           rgb0_0,
           rgb0_1,
           rgb0_2,
           rgb1_0,
           rgb1_1,
           rgb1_2,
           rgb2_0,
           rgb2_1,
           rgb2_2,
           rgb3_0,
           rgb3_1,
           rgb3_2,
           rgb4_0,
           rgb4_1,
           rgb4_2,
           rgb5_0,
           rgb5_1,
           rgb5_2,
           rgb6_0,
           rgb6_1,
           rgb6_2,
           rgb7_0,
           rgb7_1,
           rgb7_2,
           RGB0_0_1,
           RGB0_1_1,
           RGB0_2_1,
           RGB1_0_1,
           RGB1_1_1,
           RGB1_2_1,
           RGB2_0_1,
           RGB2_1_1,
           RGB2_2_1,
           RGB3_0_1,
           RGB3_1_1,
           RGB3_2_1,
           RGB4_0_1,
           RGB4_1_1,
           RGB4_2_1,
           RGB5_0_1,
           RGB5_1_1,
           RGB5_2_1,
           RGB6_0_1,
           RGB6_1_1,
           RGB6_2_1,
           RGB7_0_1,
           RGB7_1_1,
           RGB7_2_1);


  input   vstart;
  input   [11:0] fr_num;  // ufix12
  input   [2:0] addr;  // ufix3
  input   signed [17:0] rgb_0;  // sfix18_En8
  input   signed [17:0] rgb_1;  // sfix18_En8
  input   signed [17:0] rgb_2;  // sfix18_En8
  input   signed [17:0] rgb0_0;  // sfix18_En8
  input   signed [17:0] rgb0_1;  // sfix18_En8
  input   signed [17:0] rgb0_2;  // sfix18_En8
  input   signed [17:0] rgb1_0;  // sfix18_En8
  input   signed [17:0] rgb1_1;  // sfix18_En8
  input   signed [17:0] rgb1_2;  // sfix18_En8
  input   signed [17:0] rgb2_0;  // sfix18_En8
  input   signed [17:0] rgb2_1;  // sfix18_En8
  input   signed [17:0] rgb2_2;  // sfix18_En8
  input   signed [17:0] rgb3_0;  // sfix18_En8
  input   signed [17:0] rgb3_1;  // sfix18_En8
  input   signed [17:0] rgb3_2;  // sfix18_En8
  input   signed [17:0] rgb4_0;  // sfix18_En8
  input   signed [17:0] rgb4_1;  // sfix18_En8
  input   signed [17:0] rgb4_2;  // sfix18_En8
  input   signed [17:0] rgb5_0;  // sfix18_En8
  input   signed [17:0] rgb5_1;  // sfix18_En8
  input   signed [17:0] rgb5_2;  // sfix18_En8
  input   signed [17:0] rgb6_0;  // sfix18_En8
  input   signed [17:0] rgb6_1;  // sfix18_En8
  input   signed [17:0] rgb6_2;  // sfix18_En8
  input   signed [17:0] rgb7_0;  // sfix18_En8
  input   signed [17:0] rgb7_1;  // sfix18_En8
  input   signed [17:0] rgb7_2;  // sfix18_En8
  output  signed [17:0] RGB0_0_1;  // sfix18_En8
  output  signed [17:0] RGB0_1_1;  // sfix18_En8
  output  signed [17:0] RGB0_2_1;  // sfix18_En8
  output  signed [17:0] RGB1_0_1;  // sfix18_En8
  output  signed [17:0] RGB1_1_1;  // sfix18_En8
  output  signed [17:0] RGB1_2_1;  // sfix18_En8
  output  signed [17:0] RGB2_0_1;  // sfix18_En8
  output  signed [17:0] RGB2_1_1;  // sfix18_En8
  output  signed [17:0] RGB2_2_1;  // sfix18_En8
  output  signed [17:0] RGB3_0_1;  // sfix18_En8
  output  signed [17:0] RGB3_1_1;  // sfix18_En8
  output  signed [17:0] RGB3_2_1;  // sfix18_En8
  output  signed [17:0] RGB4_0_1;  // sfix18_En8
  output  signed [17:0] RGB4_1_1;  // sfix18_En8
  output  signed [17:0] RGB4_2_1;  // sfix18_En8
  output  signed [17:0] RGB5_0_1;  // sfix18_En8
  output  signed [17:0] RGB5_1_1;  // sfix18_En8
  output  signed [17:0] RGB5_2_1;  // sfix18_En8
  output  signed [17:0] RGB6_0_1;  // sfix18_En8
  output  signed [17:0] RGB6_1_1;  // sfix18_En8
  output  signed [17:0] RGB6_2_1;  // sfix18_En8
  output  signed [17:0] RGB7_0_1;  // sfix18_En8
  output  signed [17:0] RGB7_1_1;  // sfix18_En8
  output  signed [17:0] RGB7_2_1;  // sfix18_En8


  wire signed [17:0] rgb [0:2];  // sfix18_En8 [3]
  wire signed [17:0] rgb0 [0:2];  // sfix18_En8 [3]
  wire signed [17:0] rgb1 [0:2];  // sfix18_En8 [3]
  wire signed [17:0] rgb2 [0:2];  // sfix18_En8 [3]
  wire signed [17:0] rgb3 [0:2];  // sfix18_En8 [3]
  wire signed [17:0] rgb4 [0:2];  // sfix18_En8 [3]
  wire signed [17:0] rgb5 [0:2];  // sfix18_En8 [3]
  wire signed [17:0] rgb6 [0:2];  // sfix18_En8 [3]
  wire signed [17:0] rgb7 [0:2];  // sfix18_En8 [3]
  reg signed [17:0] RGB0_3 [0:2];  // sfix18_En8 [3]
  reg signed [17:0] RGB1_3 [0:2];  // sfix18_En8 [3]
  reg signed [17:0] RGB2_3 [0:2];  // sfix18_En8 [3]
  reg signed [17:0] RGB3_3 [0:2];  // sfix18_En8 [3]
  reg signed [17:0] RGB4_3 [0:2];  // sfix18_En8 [3]
  reg signed [17:0] RGB5_3 [0:2];  // sfix18_En8 [3]
  reg signed [17:0] RGB6_3 [0:2];  // sfix18_En8 [3]
  reg signed [17:0] RGB7_3 [0:2];  // sfix18_En8 [3]
  reg signed [35:0] rgb_alpha [0:2];  // sfix36_En23 [3]
  reg signed [31:0] t_0;  // int32
  reg signed [31:0] t_1;  // int32
  reg signed [31:0] t_2;  // int32
  reg signed [31:0] t_3;  // int32
  reg signed [31:0] t_4;  // int32
  reg signed [31:0] t_5;  // int32
  reg signed [31:0] t_6;  // int32
  reg signed [31:0] t_7;  // int32
  reg signed [31:0] t_8;  // int32
  reg signed [31:0] t_9;  // int32
  reg signed [17:0] t_10 [0:2];  // sfix18_En8 [3]
  reg signed [33:0] mul_temp [0:2];  // sfix34_En23 [3]
  reg signed [36:0] add_cast [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_cast_0 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_temp [0:2];  // sfix37_En23 [3]
  reg signed [33:0] mul_temp_0 [0:2];  // sfix34_En23 [3]
  reg signed [36:0] add_cast_1 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_cast_2 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_temp_0 [0:2];  // sfix37_En23 [3]
  reg signed [33:0] mul_temp_1 [0:2];  // sfix34_En23 [3]
  reg signed [36:0] add_cast_3 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_cast_4 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_temp_1 [0:2];  // sfix37_En23 [3]
  reg signed [33:0] mul_temp_2 [0:2];  // sfix34_En23 [3]
  reg signed [36:0] add_cast_5 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_cast_6 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_temp_2 [0:2];  // sfix37_En23 [3]
  reg signed [33:0] mul_temp_3 [0:2];  // sfix34_En23 [3]
  reg signed [36:0] add_cast_7 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_cast_8 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_temp_3 [0:2];  // sfix37_En23 [3]
  reg signed [33:0] mul_temp_4 [0:2];  // sfix34_En23 [3]
  reg signed [36:0] add_cast_9 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_cast_10 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_temp_4 [0:2];  // sfix37_En23 [3]
  reg signed [33:0] mul_temp_5 [0:2];  // sfix34_En23 [3]
  reg signed [36:0] add_cast_11 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_cast_12 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_temp_5 [0:2];  // sfix37_En23 [3]
  reg signed [33:0] mul_temp_6 [0:2];  // sfix34_En23 [3]
  reg signed [36:0] add_cast_13 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_cast_14 [0:2];  // sfix37_En23 [3]
  reg signed [36:0] add_temp_6 [0:2];  // sfix37_En23 [3]


  assign rgb[0] = rgb_0;
  assign rgb[1] = rgb_1;
  assign rgb[2] = rgb_2;

  assign rgb0[0] = rgb0_0;
  assign rgb0[1] = rgb0_1;
  assign rgb0[2] = rgb0_2;

  assign rgb1[0] = rgb1_0;
  assign rgb1[1] = rgb1_1;
  assign rgb1[2] = rgb1_2;

  assign rgb2[0] = rgb2_0;
  assign rgb2[1] = rgb2_1;
  assign rgb2[2] = rgb2_2;

  assign rgb3[0] = rgb3_0;
  assign rgb3[1] = rgb3_1;
  assign rgb3[2] = rgb3_2;

  assign rgb4[0] = rgb4_0;
  assign rgb4[1] = rgb4_1;
  assign rgb4[2] = rgb4_2;

  assign rgb5[0] = rgb5_0;
  assign rgb5[1] = rgb5_1;
  assign rgb5[2] = rgb5_2;

  assign rgb6[0] = rgb6_0;
  assign rgb6[1] = rgb6_1;
  assign rgb6[2] = rgb6_2;

  assign rgb7[0] = rgb7_0;
  assign rgb7[1] = rgb7_1;
  assign rgb7[2] = rgb7_2;

  always @* begin
    t_10[0] = 18'sb000110010000000000;
    t_10[1] = 18'sb000111111100000000;
    t_10[2] = 18'sb000111111100000000;

    for(t_0 = 32'sd0; t_0 <= 32'sd2; t_0 = t_0 + 32'sd1) begin
      rgb_alpha[t_0] = rgb[t_0] * 18'sb000000000000100001;
    end

    if (vstart && (fr_num == 12'b000000000000)) begin

      for(t_1 = 32'sd0; t_1 <= 32'sd2; t_1 = t_1 + 32'sd1) begin
        RGB0_3[t_1] = 18'sb000111111100000000;
        RGB1_3[t_1] = 18'sb000111111100000000;
        RGB2_3[t_1] = t_10[t_1];
        RGB3_3[t_1] = 18'sb000111111100000000;
        RGB4_3[t_1] = 18'sb000111111100000000;
        RGB5_3[t_1] = 18'sb000111111100000000;
        RGB6_3[t_1] = 18'sb000111111100000000;
        RGB7_3[t_1] = 18'sb000111111100000000;
      end

    end
    else if (addr == 3'b000) begin

      for(t_2 = 32'sd0; t_2 <= 32'sd2; t_2 = t_2 + 32'sd1) begin
        mul_temp[t_2] = rgb0[t_2] * 16'sb0111111111011111;
        add_cast[t_2] = {{3{mul_temp[t_2][33]}}, mul_temp[t_2]};
        add_cast_0[t_2] = {rgb_alpha[t_2][35], rgb_alpha[t_2]};
        add_temp[t_2] = add_cast[t_2] + add_cast_0[t_2];
        if (((add_temp[t_2][36] == 1'b0) && (add_temp[t_2][35:32] != 4'b0000)) || ((add_temp[t_2][36] == 1'b0) && (add_temp[t_2][32:15] == 18'sb011111111111111111))) begin
          RGB0_3[t_2] = 18'sb011111111111111111;
        end
        else if ((add_temp[t_2][36] == 1'b1) && (add_temp[t_2][35:32] != 4'b1111)) begin
          RGB0_3[t_2] = 18'sb100000000000000000;
        end
        else begin
          RGB0_3[t_2] = add_temp[t_2][32:15] + $signed({1'b0, add_temp[t_2][14]});
        end
        RGB1_3[t_2] = rgb1[t_2];
        RGB2_3[t_2] = rgb2[t_2];
        RGB3_3[t_2] = rgb3[t_2];
        RGB4_3[t_2] = rgb4[t_2];
        RGB5_3[t_2] = rgb5[t_2];
        RGB6_3[t_2] = rgb6[t_2];
        RGB7_3[t_2] = rgb7[t_2];
      end

    end
    else if (addr == 3'b001) begin

      for(t_3 = 32'sd0; t_3 <= 32'sd2; t_3 = t_3 + 32'sd1) begin
        RGB0_3[t_3] = rgb0[t_3];
        mul_temp_0[t_3] = rgb1[t_3] * 16'sb0111111111011111;
        add_cast_1[t_3] = {{3{mul_temp_0[t_3][33]}}, mul_temp_0[t_3]};
        add_cast_2[t_3] = {rgb_alpha[t_3][35], rgb_alpha[t_3]};
        add_temp_0[t_3] = add_cast_1[t_3] + add_cast_2[t_3];
        if (((add_temp_0[t_3][36] == 1'b0) && (add_temp_0[t_3][35:32] != 4'b0000)) || ((add_temp_0[t_3][36] == 1'b0) && (add_temp_0[t_3][32:15] == 18'sb011111111111111111))) begin
          RGB1_3[t_3] = 18'sb011111111111111111;
        end
        else if ((add_temp_0[t_3][36] == 1'b1) && (add_temp_0[t_3][35:32] != 4'b1111)) begin
          RGB1_3[t_3] = 18'sb100000000000000000;
        end
        else begin
          RGB1_3[t_3] = add_temp_0[t_3][32:15] + $signed({1'b0, add_temp_0[t_3][14]});
        end
        RGB2_3[t_3] = rgb2[t_3];
        RGB3_3[t_3] = rgb3[t_3];
        RGB4_3[t_3] = rgb4[t_3];
        RGB5_3[t_3] = rgb5[t_3];
        RGB6_3[t_3] = rgb6[t_3];
        RGB7_3[t_3] = rgb7[t_3];
      end

    end
    else if (addr == 3'b010) begin

      for(t_4 = 32'sd0; t_4 <= 32'sd2; t_4 = t_4 + 32'sd1) begin
        RGB0_3[t_4] = rgb0[t_4];
        RGB1_3[t_4] = rgb1[t_4];
        mul_temp_1[t_4] = rgb2[t_4] * 16'sb0111111111011111;
        add_cast_3[t_4] = {{3{mul_temp_1[t_4][33]}}, mul_temp_1[t_4]};
        add_cast_4[t_4] = {rgb_alpha[t_4][35], rgb_alpha[t_4]};
        add_temp_1[t_4] = add_cast_3[t_4] + add_cast_4[t_4];
        if (((add_temp_1[t_4][36] == 1'b0) && (add_temp_1[t_4][35:32] != 4'b0000)) || ((add_temp_1[t_4][36] == 1'b0) && (add_temp_1[t_4][32:15] == 18'sb011111111111111111))) begin
          RGB2_3[t_4] = 18'sb011111111111111111;
        end
        else if ((add_temp_1[t_4][36] == 1'b1) && (add_temp_1[t_4][35:32] != 4'b1111)) begin
          RGB2_3[t_4] = 18'sb100000000000000000;
        end
        else begin
          RGB2_3[t_4] = add_temp_1[t_4][32:15] + $signed({1'b0, add_temp_1[t_4][14]});
        end
        RGB3_3[t_4] = rgb3[t_4];
        RGB4_3[t_4] = rgb4[t_4];
        RGB5_3[t_4] = rgb5[t_4];
        RGB6_3[t_4] = rgb6[t_4];
        RGB7_3[t_4] = rgb7[t_4];
      end

    end
    else if (addr == 3'b011) begin

      for(t_5 = 32'sd0; t_5 <= 32'sd2; t_5 = t_5 + 32'sd1) begin
        RGB0_3[t_5] = rgb0[t_5];
        RGB1_3[t_5] = rgb1[t_5];
        RGB2_3[t_5] = rgb2[t_5];
        mul_temp_2[t_5] = rgb3[t_5] * 16'sb0111111111011111;
        add_cast_5[t_5] = {{3{mul_temp_2[t_5][33]}}, mul_temp_2[t_5]};
        add_cast_6[t_5] = {rgb_alpha[t_5][35], rgb_alpha[t_5]};
        add_temp_2[t_5] = add_cast_5[t_5] + add_cast_6[t_5];
        if (((add_temp_2[t_5][36] == 1'b0) && (add_temp_2[t_5][35:32] != 4'b0000)) || ((add_temp_2[t_5][36] == 1'b0) && (add_temp_2[t_5][32:15] == 18'sb011111111111111111))) begin
          RGB3_3[t_5] = 18'sb011111111111111111;
        end
        else if ((add_temp_2[t_5][36] == 1'b1) && (add_temp_2[t_5][35:32] != 4'b1111)) begin
          RGB3_3[t_5] = 18'sb100000000000000000;
        end
        else begin
          RGB3_3[t_5] = add_temp_2[t_5][32:15] + $signed({1'b0, add_temp_2[t_5][14]});
        end
        RGB4_3[t_5] = rgb4[t_5];
        RGB5_3[t_5] = rgb5[t_5];
        RGB6_3[t_5] = rgb6[t_5];
        RGB7_3[t_5] = rgb7[t_5];
      end

    end
    else if (addr == 3'b100) begin

      for(t_6 = 32'sd0; t_6 <= 32'sd2; t_6 = t_6 + 32'sd1) begin
        RGB0_3[t_6] = rgb0[t_6];
        RGB1_3[t_6] = rgb1[t_6];
        RGB2_3[t_6] = rgb2[t_6];
        RGB3_3[t_6] = rgb3[t_6];
        mul_temp_3[t_6] = rgb4[t_6] * 16'sb0111111111011111;
        add_cast_7[t_6] = {{3{mul_temp_3[t_6][33]}}, mul_temp_3[t_6]};
        add_cast_8[t_6] = {rgb_alpha[t_6][35], rgb_alpha[t_6]};
        add_temp_3[t_6] = add_cast_7[t_6] + add_cast_8[t_6];
        if (((add_temp_3[t_6][36] == 1'b0) && (add_temp_3[t_6][35:32] != 4'b0000)) || ((add_temp_3[t_6][36] == 1'b0) && (add_temp_3[t_6][32:15] == 18'sb011111111111111111))) begin
          RGB4_3[t_6] = 18'sb011111111111111111;
        end
        else if ((add_temp_3[t_6][36] == 1'b1) && (add_temp_3[t_6][35:32] != 4'b1111)) begin
          RGB4_3[t_6] = 18'sb100000000000000000;
        end
        else begin
          RGB4_3[t_6] = add_temp_3[t_6][32:15] + $signed({1'b0, add_temp_3[t_6][14]});
        end
        RGB5_3[t_6] = rgb5[t_6];
        RGB6_3[t_6] = rgb6[t_6];
        RGB7_3[t_6] = rgb7[t_6];
      end

    end
    else if (addr == 3'b101) begin

      for(t_7 = 32'sd0; t_7 <= 32'sd2; t_7 = t_7 + 32'sd1) begin
        RGB0_3[t_7] = rgb0[t_7];
        RGB1_3[t_7] = rgb1[t_7];
        RGB2_3[t_7] = rgb2[t_7];
        RGB3_3[t_7] = rgb3[t_7];
        RGB4_3[t_7] = rgb4[t_7];
        mul_temp_4[t_7] = rgb5[t_7] * 16'sb0111111111011111;
        add_cast_9[t_7] = {{3{mul_temp_4[t_7][33]}}, mul_temp_4[t_7]};
        add_cast_10[t_7] = {rgb_alpha[t_7][35], rgb_alpha[t_7]};
        add_temp_4[t_7] = add_cast_9[t_7] + add_cast_10[t_7];
        if (((add_temp_4[t_7][36] == 1'b0) && (add_temp_4[t_7][35:32] != 4'b0000)) || ((add_temp_4[t_7][36] == 1'b0) && (add_temp_4[t_7][32:15] == 18'sb011111111111111111))) begin
          RGB5_3[t_7] = 18'sb011111111111111111;
        end
        else if ((add_temp_4[t_7][36] == 1'b1) && (add_temp_4[t_7][35:32] != 4'b1111)) begin
          RGB5_3[t_7] = 18'sb100000000000000000;
        end
        else begin
          RGB5_3[t_7] = add_temp_4[t_7][32:15] + $signed({1'b0, add_temp_4[t_7][14]});
        end
        RGB6_3[t_7] = rgb6[t_7];
        RGB7_3[t_7] = rgb7[t_7];
      end

    end
    else if (addr == 3'b110) begin

      for(t_9 = 32'sd0; t_9 <= 32'sd2; t_9 = t_9 + 32'sd1) begin
        RGB0_3[t_9] = rgb0[t_9];
        RGB1_3[t_9] = rgb1[t_9];
        RGB2_3[t_9] = rgb2[t_9];
        RGB3_3[t_9] = rgb3[t_9];
        RGB4_3[t_9] = rgb4[t_9];
        RGB5_3[t_9] = rgb5[t_9];
        mul_temp_5[t_9] = rgb6[t_9] * 16'sb0111111111011111;
        add_cast_11[t_9] = {{3{mul_temp_5[t_9][33]}}, mul_temp_5[t_9]};
        add_cast_12[t_9] = {rgb_alpha[t_9][35], rgb_alpha[t_9]};
        add_temp_5[t_9] = add_cast_11[t_9] + add_cast_12[t_9];
        if (((add_temp_5[t_9][36] == 1'b0) && (add_temp_5[t_9][35:32] != 4'b0000)) || ((add_temp_5[t_9][36] == 1'b0) && (add_temp_5[t_9][32:15] == 18'sb011111111111111111))) begin
          RGB6_3[t_9] = 18'sb011111111111111111;
        end
        else if ((add_temp_5[t_9][36] == 1'b1) && (add_temp_5[t_9][35:32] != 4'b1111)) begin
          RGB6_3[t_9] = 18'sb100000000000000000;
        end
        else begin
          RGB6_3[t_9] = add_temp_5[t_9][32:15] + $signed({1'b0, add_temp_5[t_9][14]});
        end
        RGB7_3[t_9] = rgb7[t_9];
      end

    end
    else begin

      for(t_8 = 32'sd0; t_8 <= 32'sd2; t_8 = t_8 + 32'sd1) begin
        RGB0_3[t_8] = rgb0[t_8];
        RGB1_3[t_8] = rgb1[t_8];
        RGB2_3[t_8] = rgb2[t_8];
        RGB3_3[t_8] = rgb3[t_8];
        RGB4_3[t_8] = rgb4[t_8];
        RGB5_3[t_8] = rgb5[t_8];
        RGB6_3[t_8] = rgb6[t_8];
        mul_temp_6[t_8] = rgb7[t_8] * 16'sb0111111111011111;
        add_cast_13[t_8] = {{3{mul_temp_6[t_8][33]}}, mul_temp_6[t_8]};
        add_cast_14[t_8] = {rgb_alpha[t_8][35], rgb_alpha[t_8]};
        add_temp_6[t_8] = add_cast_13[t_8] + add_cast_14[t_8];
        if (((add_temp_6[t_8][36] == 1'b0) && (add_temp_6[t_8][35:32] != 4'b0000)) || ((add_temp_6[t_8][36] == 1'b0) && (add_temp_6[t_8][32:15] == 18'sb011111111111111111))) begin
          RGB7_3[t_8] = 18'sb011111111111111111;
        end
        else if ((add_temp_6[t_8][36] == 1'b1) && (add_temp_6[t_8][35:32] != 4'b1111)) begin
          RGB7_3[t_8] = 18'sb100000000000000000;
        end
        else begin
          RGB7_3[t_8] = add_temp_6[t_8][32:15] + $signed({1'b0, add_temp_6[t_8][14]});
        end
      end

    end
  end



  assign RGB0_0_1 = RGB0_3[0];

  assign RGB0_1_1 = RGB0_3[1];

  assign RGB0_2_1 = RGB0_3[2];

  assign RGB1_0_1 = RGB1_3[0];

  assign RGB1_1_1 = RGB1_3[1];

  assign RGB1_2_1 = RGB1_3[2];

  assign RGB2_0_1 = RGB2_3[0];

  assign RGB2_1_1 = RGB2_3[1];

  assign RGB2_2_1 = RGB2_3[2];

  assign RGB3_0_1 = RGB3_3[0];

  assign RGB3_1_1 = RGB3_3[1];

  assign RGB3_2_1 = RGB3_3[2];

  assign RGB4_0_1 = RGB4_3[0];

  assign RGB4_1_1 = RGB4_3[1];

  assign RGB4_2_1 = RGB4_3[2];

  assign RGB5_0_1 = RGB5_3[0];

  assign RGB5_1_1 = RGB5_3[1];

  assign RGB5_2_1 = RGB5_3[2];

  assign RGB6_0_1 = RGB6_3[0];

  assign RGB6_1_1 = RGB6_3[1];

  assign RGB6_2_1 = RGB6_3[2];

  assign RGB7_0_1 = RGB7_3[0];

  assign RGB7_1_1 = RGB7_3[1];

  assign RGB7_2_1 = RGB7_3[2];

endmodule  // K_Means_ip_src_MATLAB_Function

